defmodule SofiTrader.Kalshi.Alert do
  @moduledoc """
  Schema for Kalshi alerts.

  Tracks all alerts generated by strategies, including:
  - Alert type and severity
  - Message and payload data
  - Delivery status and acknowledgment
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias SofiTrader.Kalshi.Strategy

  @type t :: %__MODULE__{}

  @alert_types [
    "price_threshold",     # Price crossed configured threshold
    "volume_spike",        # Volume exceeded threshold
    "price_change",        # Significant price movement
    "order_placed",        # Auto-bid placed an order
    "order_filled",        # Order was filled
    "order_canceled",      # Order was canceled
    "position_opened",     # New position opened
    "position_closed",     # Position closed
    "settlement",          # Market settled
    "error"                # Strategy error
  ]

  @severities ["info", "warning", "critical"]
  @channels ["pubsub", "webhook", "ui"]

  schema "kalshi_alerts" do
    field :market_ticker, :string
    field :alert_type, :string
    field :severity, :string, default: "info"
    field :message, :string
    field :data, :map
    field :channels_sent, {:array, :string}
    field :acknowledged, :boolean, default: false
    field :acknowledged_at, :utc_datetime

    belongs_to :strategy, Strategy

    timestamps()
  end

  @doc """
  Changeset for creating an alert.
  """
  def changeset(alert, attrs) do
    alert
    |> cast(attrs, [
      :strategy_id, :market_ticker, :alert_type, :severity,
      :message, :data, :channels_sent, :acknowledged, :acknowledged_at
    ])
    |> validate_required([:alert_type, :message])
    |> validate_inclusion(:alert_type, @alert_types)
    |> validate_inclusion(:severity, @severities)
    |> validate_channels()
    |> foreign_key_constraint(:strategy_id)
  end

  defp validate_channels(changeset) do
    channels = get_field(changeset, :channels_sent) || []

    if Enum.all?(channels, &(&1 in @channels)) do
      changeset
    else
      add_error(changeset, :channels_sent, "contains invalid channel")
    end
  end

  @doc """
  Mark an alert as acknowledged.
  """
  def acknowledge_changeset(alert) do
    alert
    |> change(%{
      acknowledged: true,
      acknowledged_at: DateTime.utc_now()
    })
  end

  @doc """
  Build an alert struct for a price threshold event.
  """
  def price_threshold(strategy_id, ticker, side, price, threshold, direction) do
    %{
      strategy_id: strategy_id,
      market_ticker: ticker,
      alert_type: "price_threshold",
      severity: "warning",
      message: "#{String.upcase(side)} price #{direction} threshold: #{price}¢ (threshold: #{threshold}¢)",
      data: %{
        "side" => side,
        "current_price" => price,
        "threshold" => threshold,
        "direction" => direction
      }
    }
  end

  @doc """
  Build an alert struct for a volume spike.
  """
  def volume_spike(strategy_id, ticker, volume, threshold) do
    %{
      strategy_id: strategy_id,
      market_ticker: ticker,
      alert_type: "volume_spike",
      severity: "info",
      message: "Volume spike detected: #{volume} contracts (threshold: #{threshold})",
      data: %{
        "volume" => volume,
        "threshold" => threshold
      }
    }
  end

  @doc """
  Build an alert struct for order placement.
  """
  def order_placed(strategy_id, ticker, order) do
    %{
      strategy_id: strategy_id,
      market_ticker: ticker,
      alert_type: "order_placed",
      severity: "info",
      message: "Order placed: #{order.action} #{order.count} #{String.upcase(order.side)} @ #{order.price_cents}¢",
      data: %{
        "order_id" => order.order_id,
        "side" => order.side,
        "action" => order.action,
        "count" => order.count,
        "price_cents" => order.price_cents
      }
    }
  end

  @doc """
  Build an alert struct for order fill.
  """
  def order_filled(strategy_id, ticker, order) do
    %{
      strategy_id: strategy_id,
      market_ticker: ticker,
      alert_type: "order_filled",
      severity: "info",
      message: "Order filled: #{order.filled_count}/#{order.count} #{String.upcase(order.side)} @ #{order.avg_fill_price_cents}¢",
      data: %{
        "order_id" => order.order_id,
        "filled_count" => order.filled_count,
        "count" => order.count,
        "avg_fill_price_cents" => order.avg_fill_price_cents
      }
    }
  end

  @doc """
  Build an alert struct for errors.
  """
  def error(strategy_id, ticker, error_message, error_data \\ %{}) do
    %{
      strategy_id: strategy_id,
      market_ticker: ticker,
      alert_type: "error",
      severity: "critical",
      message: "Strategy error: #{error_message}",
      data: error_data
    }
  end
end
